<?php
/**
 * TL_ROOT/system/modules/avatar/languages/ro/avatar.php 
 * 
 * Contao extension: avatar 1.0.1 stable 
 * Romanian translation file 
 * 
 * Copyright : (c) 2008,2009,2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Ionuţ Purcaru (purcaruionut) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['avatar']['file']['0'] = "Încarcă un nou avatar";
$GLOBALS['TL_LANG']['avatar']['file']['1'] = "Tipuri de fişiere permise: %s.<br/> Mărime maximă fişier: %s bytes.<br/> Dimensiuni maxime: %s x %s pixeli.";
$GLOBALS['TL_LANG']['avatar']['save'] = "Salvează avatar";
$GLOBALS['TL_LANG']['avatar']['reset'] = "Resetează avatar";
$GLOBALS['TL_LANG']['avatar']['invalidfilext'] = "<em>%s</em> are o extensie invalidă.";
$GLOBALS['TL_LANG']['avatar']['errinisize'] = "<em>%s</em> depăşeşte upload_max_filesize în php.ini.";
$GLOBALS['TL_LANG']['avatar']['errformsize'] = "<em>%s</em> depăşeşte MAX_FILE_SIZE în formular.";
$GLOBALS['TL_LANG']['avatar']['errpartial'] = "<em>%s</em> a fost doar parţial încărcat.";
$GLOBALS['TL_LANG']['avatar']['notmpdir'] = "Nu există un folder temporar.";
$GLOBALS['TL_LANG']['avatar']['cantwrite'] = "<em>%s</em> nu se poate scrie fişierul pe disc.";
$GLOBALS['TL_LANG']['avatar']['errorno'] = "<em>%s</em> eroare de transmitere %s.";
$GLOBALS['TL_LANG']['avatar']['filetoobig'] = "<em>%s</em> depăşeşte mărimea maximă admisă.";
$GLOBALS['TL_LANG']['avatar']['imgtoobig'] = "<em>%s</em> depăşeşte dimensiunile permise.";
 
?>
