<?php
/**
 * TL_ROOT/system/modules/avatar/languages/ro/tl_settings.php 
 * 
 * Contao extension: avatar 1.0.1 stable 
 * Romanian translation file 
 * 
 * Copyright : (c) 2008,2009,2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Ionuţ Purcaru (purcaruionut) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['avatar_legend'] = "Avatar";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['0'] = "Director destinaţie";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['1'] = "Selectaţi un director destinaţie. Locaţia sugerată este <em>tl_files/avatars</em>.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['0'] = "Mărime maximă";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['1'] = "Mărime maximă în bytes";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['0'] = "Dimensiuni maxime";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['1'] = "Selectaţi maximele pentru lăţime şi înălţime în pixeli.";
 
?>
