<?php
/**
 * TL_ROOT/system/modules/avatar/languages/de/avatar.php 
 * 
 * TYPOlight extension: avatar 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : (c) 2008,2009,2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Koch (acenes), http://ibk-software.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['avatar']['file']['0'] = "Neuen Avatar hochladen";
$GLOBALS['TL_LANG']['avatar']['file']['1'] = "Erlaubte Dateitypen: %s.<br/>\nMaximale Dateigrösse: %s Byte.<br/>\nMaximale Abmessungen: %s x %s Pixel.";
$GLOBALS['TL_LANG']['avatar']['save'] = "Avatar speichern";
$GLOBALS['TL_LANG']['avatar']['reset'] = "Zurücksetzen auf Vorgabe";
$GLOBALS['TL_LANG']['avatar']['invalidfilext'] = "<em>%s</em> hat eine ungültige Erweiterung.";
$GLOBALS['TL_LANG']['avatar']['errinisize'] = "<em>%s</em> überschreitet upload_max_filesize in php.ini.";
$GLOBALS['TL_LANG']['avatar']['errformsize'] = "<em>%s</em> überschreitet MAX_FILE_SIZE im Formular.";
$GLOBALS['TL_LANG']['avatar']['errpartial'] = "<em>%s</em> wurde nur teilweise hochgeladen.";
$GLOBALS['TL_LANG']['avatar']['notmpdir'] = "Kein Verzeichnis für temporäre dateien vorhanden.";
$GLOBALS['TL_LANG']['avatar']['cantwrite'] = "<em>%s</em> fehler beim Schreiben auf Festplatte.";
$GLOBALS['TL_LANG']['avatar']['errorno'] = "<em>%s</em> Hochladefehler %s.";
$GLOBALS['TL_LANG']['avatar']['filetoobig'] = "<em>%s</em> überschreitet die erlaubte Dateigrösse.";
$GLOBALS['TL_LANG']['avatar']['imgtoobig'] = "<em>%s</em> überschreitet die erlaubten Abmessungen.";
 
?>
