<?php
/**
 * TL_ROOT/system/modules/avatar/languages/de/modules.php 
 * 
 * TYPOlight extension: avatar 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : (c) 2008,2009,2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Koch (acenes), http://ibk-software.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['avatar'] = "Avatar";
$GLOBALS['TL_LANG']['FMD']['avatar']['0'] = "Avatar";
$GLOBALS['TL_LANG']['FMD']['avatar']['1'] = "Frontend Module für Mitglieder zum ändern ihres Avatars.";
 
?>
