<?php
/**
 * TL_ROOT/system/modules/avatar/languages/de/tl_settings.php 
 * 
 * TYPOlight extension: avatar 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : (c) 2008,2009,2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Koch (acenes), http://ibk-software.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['avatar_legend'] = "Avatar";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['0'] = "Basisverzeichnis";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['1'] = "Basisverzeichnis auswählen. Der empfohlene Ort is <em>tl_files/avatars</em>.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['0'] = "Maximale Dateigrösse.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['1'] = "Maximale Dateigrösse in Byte.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['0'] = "Maximale Abmessungen";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['1'] = "Auswahl der maximalen Breite und Höhe in Pixeln.";
 
?>
