<?php
/**
 * TL_ROOT/system/modules/avatar/languages/lv/avatar.php 
 * 
 * Contao extension: avatar 1.0.1 stable 
 * Latvian translation file 
 * 
 * Copyright : (c) 2008,2009,2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Maris Celmins (warrior) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['avatar']['file']['0'] = "Ielādēt jaunu avataru";
$GLOBALS['TL_LANG']['avatar']['file']['1'] = "Atļautie failu tipi: %s.<br/>\nFaila max izmērs: %s bytes.<br/>\nMax dimensijas: %s x %s pixels.";
$GLOBALS['TL_LANG']['avatar']['save'] = "Saglabāt avataru";
$GLOBALS['TL_LANG']['avatar']['reset'] = "Atjaunot noklusēto";
$GLOBALS['TL_LANG']['avatar']['invalidfilext'] = "<em>%s</em> ir nederīgs paplašinājums.";
$GLOBALS['TL_LANG']['avatar']['errinisize'] = "<em>%s</em> pārsniedz upload_max_filesize php.ini failā.";
$GLOBALS['TL_LANG']['avatar']['errformsize'] = "<em>%s</em> pārsniedz MAX_FILE_SIZE formā.";
$GLOBALS['TL_LANG']['avatar']['errpartial'] = "<em>%s</em> augšupielādēts tikai daļēji.";
$GLOBALS['TL_LANG']['avatar']['notmpdir'] = "Pazaudēta īslaicīgās lietošanas mape.";
$GLOBALS['TL_LANG']['avatar']['cantwrite'] = "<em>%s</em> nespēja ierakstīt diskā.";
$GLOBALS['TL_LANG']['avatar']['errorno'] = "<em>%s</em> augšupielādes kļūda %s.";
$GLOBALS['TL_LANG']['avatar']['filetoobig'] = "<em>%s</em> pārsniedz atļauto apjomu.";
$GLOBALS['TL_LANG']['avatar']['imgtoobig'] = "<em>%s</em> pārsniedz atļautos izmērus.";
 
?>
