<?php
/**
 * TL_ROOT/system/modules/avatar/languages/lv/tl_member.php 
 * 
 * Contao extension: avatar 1.0.1 stable 
 * Latvian translation file 
 * 
 * Copyright : (c) 2008,2009,2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Maris Celmins (warrior) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_member']['avatar_legend'] = "Avatar";
$GLOBALS['TL_LANG']['tl_member']['avatar']['0'] = "Avatar";
$GLOBALS['TL_LANG']['tl_member']['avatar']['1'] = "Šeit varat ielādēt savu avataru vai logo.";
 
?>
