<?php
/**
 * TL_ROOT/system/modules/avatar/languages/lv/tl_settings.php 
 * 
 * Contao extension: avatar 1.0.1 stable 
 * Latvian translation file 
 * 
 * Copyright : (c) 2008,2009,2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Maris Celmins (warrior) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['avatar_legend'] = "Avatar";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['0'] = "Pamata mape";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['1'] = "Izvēlieties pamata mapi. Pēc noklusējuma tiek piedāvāta <em>tl_files/avatars</em> mape.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['0'] = "Faila max izmērs";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['1'] = "Failu max izmērs bitos.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['0'] = "Max dimensijas";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['1'] = "Max platumu un augstumu norādiet pikseļos.";
 
?>
