<?php
/**
 * TL_ROOT/system/modules/avatar/languages/pl/avatar.php 
 * 
 * TYPOlight extension: avatar 0.2.0 stable 
 * Polish translation file 
 * 
 * Copyright : (c) 2008 IBK Software AG 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['avatar']['file']['0'] = "Wgraj nowy avatar";
$GLOBALS['TL_LANG']['avatar']['file']['1'] = "Dopuszczalne typy plików: %s.<br/>\nMaksymalna wielkość: %s bajtów.<br/>\nMaksymalne wymiary: %s x %s piksli.";
$GLOBALS['TL_LANG']['avatar']['save'] = "Zachowaj avatar";
$GLOBALS['TL_LANG']['avatar']['reset'] = "Przywróć domyślny";
$GLOBALS['TL_LANG']['avatar']['invalidfilext'] = "<em>%s</em> posiada niepoprawne rozszerzenie.";
$GLOBALS['TL_LANG']['avatar']['errinisize'] = "<em>%s</em> przekroczył maksymalny rozmiar przesyłanego pliku ustalony w php.ini.";
$GLOBALS['TL_LANG']['avatar']['errformsize'] = "<em>%s</em> przekroczył maksymalny rozmiar pliku ustalony w php.ini.";
$GLOBALS['TL_LANG']['avatar']['errpartial'] = "<em>%s</em> został tylko częściowo przesłany.";
$GLOBALS['TL_LANG']['avatar']['notmpdir'] = "Brak folderu plików tymczasowych";
$GLOBALS['TL_LANG']['avatar']['cantwrite'] = "Błąd zapisu <em>%s</em> na dysk.";
$GLOBALS['TL_LANG']['avatar']['errorno'] = "<em>%s</em> błąd wysyłania %s.";
$GLOBALS['TL_LANG']['avatar']['filetoobig'] = "<em>%s</em> przekroczył maksymalny rozmiar pliku.";
$GLOBALS['TL_LANG']['avatar']['imgtoobig'] = "<em>%s</em> przekroczył dopuszczalne wymiary.";
 
?>
