<?php
/**
 * TL_ROOT/system/modules/avatar/languages/pl/modules.php 
 * 
 * TYPOlight extension: avatar 0.2.0 stable 
 * Polish translation file 
 * 
 * Copyright : (c) 2008 IBK Software AG 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['avatar'] = "Avatar";
$GLOBALS['TL_LANG']['FMD']['avatar']['0'] = "Avatar";
$GLOBALS['TL_LANG']['FMD']['avatar']['1'] = "Moduł pozwalający członkom edytować ich avatar.";
 
?>
