<?php
/**
 * TL_ROOT/system/modules/avatar/languages/pl/tl_settings.php 
 * 
 * TYPOlight extension: avatar 0.2.0 stable 
 * Polish translation file 
 * 
 * Copyright : (c) 2008 IBK Software AG 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Marcin Lachowski (qrczak), http://www.typolight.pl 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['0'] = "Folder avatarów";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['1'] = "Wybierz folder, w którym będą przetrzymywane avatary. Sugerowana lokalizacja to <em>tl_files/avatars</em>.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['0'] = "Maksymalny rozmiar pliku avatara";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['1'] = "Maksymalny rozmiar pliku avatara w bajtach.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['0'] = "Maksymalne wymiary avatara";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['1'] = "Wpisz maksymalną szerokość i wysokość avatara w pikslach.";
 
?>
