<?php
/**
 * TL_ROOT/system/modules/avatar/languages/nl/avatar.php 
 * 
 * Contao extension: avatar 1.0.1 stable 
 * Dutch translation file 
 * 
 * Copyright : (c) 2008,2009,2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Hamers (pchammer) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['avatar']['file']['0'] = "Nieuwe avatar uploaden";
$GLOBALS['TL_LANG']['avatar']['file']['1'] = "Toegestane bestandtypes: %s.<br/> Maximum bestandsgrootte: %s bytes.<br/> Maximale afmetingen: %s x %s pixels.";
$GLOBALS['TL_LANG']['avatar']['save'] = "Bewaar avatar";
$GLOBALS['TL_LANG']['avatar']['reset'] = "Reset naar standaard";
$GLOBALS['TL_LANG']['avatar']['invalidfilext'] = "<em>%s</em> onjuiste extensie.";
$GLOBALS['TL_LANG']['avatar']['errinisize'] = "<em>%s</em> overschrijdt maximale upload grootte in php.ini.";
$GLOBALS['TL_LANG']['avatar']['errformsize'] = "<em>%s</em> overschrijdt MAX_FILE_GROOTTE in het formulier.";
$GLOBALS['TL_LANG']['avatar']['errpartial'] = "<em>%s</em> is slechts gedeeltelijk geupload.";
$GLOBALS['TL_LANG']['avatar']['notmpdir'] = "Mist een tijdelijke map.";
$GLOBALS['TL_LANG']['avatar']['cantwrite'] = "<em>%s</em> fout bij het opslaan.";
$GLOBALS['TL_LANG']['avatar']['errorno'] = "<em>%s</em> upload fout %s.";
$GLOBALS['TL_LANG']['avatar']['filetoobig'] = "<em>%s</em> overschrijdt toegestane maximale grootte.";
$GLOBALS['TL_LANG']['avatar']['imgtoobig'] = "<em>%s</em> overschrijdt toegestane maximale afmetingen.";
 
?>
