<?php
/**
 * TL_ROOT/system/modules/avatar/languages/nl/tl_settings.php 
 * 
 * Contao extension: avatar 1.0.1 stable 
 * Dutch translation file 
 * 
 * Copyright : (c) 2008,2009,2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Hamers (pchammer) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['avatar_legend'] = "Avatar";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['0'] = "Avatar base directory";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['1'] = "Selecteer het avatar basis bestand. De voorkeurs locatie is <em>tl_files/avatars</em>.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['0'] = "Maximum avatar bestandsgrootte";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['1'] = "Maximum avatar bestandsgrootte in bytes.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['0'] = "Maximale avatar afmetingen";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['1'] = "Selecteer de maximale breedte en hoogte van avatar in pixels.";
 
?>
