<?php
/**
 * TL_ROOT/system/modules/avatar/languages/nl/tl_user.php 
 * 
 * Contao extension: avatar 1.0.1 stable 
 * Dutch translation file 
 * 
 * Copyright : (c) 2008,2009,2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Hamers (pchammer) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['avatar_legend'] = "Avatar";
$GLOBALS['TL_LANG']['tl_user']['avatar']['0'] = "Avatar";
$GLOBALS['TL_LANG']['tl_user']['avatar']['1'] = "Hier kunt een avatar of logo uploaden.";
 
?>
