<?php
/**
 * TL_ROOT/system/modules/avatar/languages/lv/tl_member.php 
 * 
 * Contao extension: avatar 2.0.3 stable 
 * Latvian translation file 
 * 
 * Copyright : &copy; 2013 Kirsten Roschanski, &copy; 2013 Tristan Lins 
 * License   : LGPL 
 * Author    : Kirsten Roschanski (katgirl), http://kirsten-roschanski.de 
 * Translator: Maris Celmins (warrior), http://maris.celmins.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_member']['avatar_legend'] = "Avatar";
$GLOBALS['TL_LANG']['tl_member']['avatar']['0'] = "Avatar";
$GLOBALS['TL_LANG']['tl_member']['avatar']['1'] = "Šeit jūs varat augšupielādēt avataru vai logo.";
 
?>
