<?php
/**
 * TL_ROOT/system/modules/avatar/languages/lv/tl_settings.php 
 * 
 * Contao extension: avatar 2.0.3 stable 
 * Latvian translation file 
 * 
 * Copyright : &copy; 2013 Kirsten Roschanski, &copy; 2013 Tristan Lins 
 * License   : LGPL 
 * Author    : Kirsten Roschanski (katgirl), http://kirsten-roschanski.de 
 * Translator: Maris Celmins (warrior), http://maris.celmins.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['avatar_legend'] = "Avatar";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['0'] = "Bāzes direktorija";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['1'] = "Izvēlaties bāzes direktoriju. Rekomendējamā izvietošana ir <em>tl_files/avatars</em>.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['0'] = "Faila max apjoms";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['1'] = "Faila maksimālais apjoms bitos.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['0'] = "Maksimālās dimensijas";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['1'] = "Ivēlaties maksimālās platuma un garuma dimensijas pikseļos.";
 
?>
