<?php
/**
 * TL_ROOT/system/modules/avatar/languages/ru/avatar.php 
 * 
 * Contao extension: avatar 1.0.1 stable 
 * Russian translation file 
 * 
 * Copyright : (c) 2008,2009,2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['avatar']['file']['0'] = "Загрузить аватар";
$GLOBALS['TL_LANG']['avatar']['file']['1'] = "Разрешенные типы файлов: %s.<br/> Максимальный размер файла: %s байт.<br/> Максимальные размеры: %s x %s пикселей.";
$GLOBALS['TL_LANG']['avatar']['save'] = "Сохранить аватар";
$GLOBALS['TL_LANG']['avatar']['reset'] = "Сбросить на умолчания";
$GLOBALS['TL_LANG']['avatar']['invalidfilext'] = "<em>%s</em> имеет недопустимое расширение.";
$GLOBALS['TL_LANG']['avatar']['errinisize'] = "<em>%s</em> превышает upload_max_filesize в php.ini.";
$GLOBALS['TL_LANG']['avatar']['errformsize'] = "<em>%s</em> превышает MAX_FILE_SIZE в форме.";
$GLOBALS['TL_LANG']['avatar']['errpartial'] = "<em>%s</em> был загружен частично.";
$GLOBALS['TL_LANG']['avatar']['notmpdir'] = "Потеряна временная папка.";
$GLOBALS['TL_LANG']['avatar']['cantwrite'] = "<em>%s</em> не удалось записать файл на диск.";
$GLOBALS['TL_LANG']['avatar']['errorno'] = "<em>%s</em> ошибка загрузки %s.";
$GLOBALS['TL_LANG']['avatar']['filetoobig'] = "<em>%s</em> превышает допустимый максимальный размер.";
$GLOBALS['TL_LANG']['avatar']['imgtoobig'] = "<em>%s</em> превышает допустимые размеры.";
 
?>
