<?php
/**
 * TL_ROOT/system/modules/avatar/languages/ru/modules.php 
 * 
 * Contao extension: avatar 1.0.1 stable 
 * Russian translation file 
 * 
 * Copyright : (c) 2008,2009,2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['avatar'] = "Аватар";
$GLOBALS['TL_LANG']['FMD']['avatar']['0'] = "Аватар";
$GLOBALS['TL_LANG']['FMD']['avatar']['1'] = "Модуль внешнего интерфейса, дающий возможность участникам изменять свой аватар.";
 
?>
