<?php
/**
 * TL_ROOT/system/modules/avatar/languages/ru/tl_settings.php 
 * 
 * Contao extension: avatar 1.0.1 stable 
 * Russian translation file 
 * 
 * Copyright : (c) 2008,2009,2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['avatar_legend'] = "Аватар";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['0'] = "Базовая папка аватар";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['1'] = "Выберите базовую папку аватар. Возможное расположение <em>tl_files/avatars</em>.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['0'] = "Максимальный размер файла аватара";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['1'] = "Максимальный размер файла аватара в байтах.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['0'] = "Максимальные размеры аватара";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['1'] = "Выберите максимальную ширину и высоту аватара в пикселях.";
 
?>
