<?php
/**
 * TL_ROOT/system/modules/avatar/languages/cs/modules.php 
 * 
 * Contao extension: avatar 2.0.4 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2013 Kirsten Roschanski, &copy; 2013 Tristan Lins 
 * License   : LGPL 
 * Author    : Kirsten Roschanski (katgirl), http://kirsten-roschanski.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['avatar'] = "Avatar";
$GLOBALS['TL_LANG']['FMD']['avatar']['0'] = "Avatar";
$GLOBALS['TL_LANG']['FMD']['avatar']['1'] = "Frontend modul umožňuje uživatelům editovat avatary.";
 
?>
