<?php
/**
 * TL_ROOT/system/modules/avatar/languages/cs/tl_member.php 
 * 
 * Contao extension: avatar 2.0.4 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2013 Kirsten Roschanski, &copy; 2013 Tristan Lins 
 * License   : LGPL 
 * Author    : Kirsten Roschanski (katgirl), http://kirsten-roschanski.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_member']['avatar_legend'] = "Avatar";
$GLOBALS['TL_LANG']['tl_member']['avatar']['0'] = "Avatar";
$GLOBALS['TL_LANG']['tl_member']['avatar']['1'] = "Zde můžete nahrát avatar nebo logo.";
 
?>
