<?php
/**
 * TL_ROOT/system/modules/avatar/languages/cs/tl_settings.php 
 * 
 * Contao extension: avatar 2.0.4 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; 2013 Kirsten Roschanski, &copy; 2013 Tristan Lins 
 * License   : LGPL 
 * Author    : Kirsten Roschanski (katgirl), http://kirsten-roschanski.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['avatar_legend'] = "Avatar";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['0'] = "Základní adresář";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['1'] = "Vyberte základní adresář. Navržené umístění je <em>tl_files/avatars</em>.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['0'] = "Maximální velikost souboru";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['1'] = "Maximální velikost souboru v bytes.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['0'] = "Maximální rozměry";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['1'] = "Vyberte maximální šířku a výšku v pixelech.";
 
?>
