<?php
/**
 * TL_ROOT/system/modules/avatar/languages/it/avatar.php 
 * 
 * TYPOlight extension: avatar 0.2.0 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2008 IBK Software AG 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['avatar']['file']['0'] = "Carica nuovo avatar";
$GLOBALS['TL_LANG']['avatar']['file']['1'] = "Tipi di file ammessi: %s.<br/>\nDimensione massima del file: %s byte.<br/>Dimensioni massime: %s x %s pixel.";
$GLOBALS['TL_LANG']['avatar']['save'] = "Salva avatar";
$GLOBALS['TL_LANG']['avatar']['reset'] = "Reset alle impostazioni predefinite";
$GLOBALS['TL_LANG']['avatar']['invalidfilext'] = "<em>%s</em> ha estensione non valida.";
$GLOBALS['TL_LANG']['avatar']['errinisize'] = "<em>%s</em> supera la upload_max_filesize in php.ini.";
$GLOBALS['TL_LANG']['avatar']['errformsize'] = "<em>%s</em> supera MAX_FILE_SIZE nel form.";
$GLOBALS['TL_LANG']['avatar']['errpartial'] = "<em>%s</em> è stato caricato solo parzialmente.";
$GLOBALS['TL_LANG']['avatar']['notmpdir'] = "Manca una cartella temporanea.";
$GLOBALS['TL_LANG']['avatar']['cantwrite'] = "<em>%s</em> scrittura sul disco fallita.";
$GLOBALS['TL_LANG']['avatar']['errorno'] = "<em>%s</em> errore di caricamento %s.";
$GLOBALS['TL_LANG']['avatar']['filetoobig'] = "<em>%s</em> supera la dimensione massima ammessa.";
$GLOBALS['TL_LANG']['avatar']['imgtoobig'] = "<em>%s</em> supera le dimensioni ammesse.";
 
?>
