<?php
/**
 * TL_ROOT/system/modules/avatar/languages/it/tl_settings.php 
 * 
 * TYPOlight extension: avatar 0.2.0 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2008 IBK Software AG 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['0'] = "Cartella base per l'avatar";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['1'] = "Seleziona la cartella base del file avatar. Il percorso suggerito è<em>tl_files/avatars</em>.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['0'] = "Dimensione massima file avatar";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['1'] = "Dimensione massima file avatar in byte.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['0'] = "Dimensioni massime dell'avatar";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['1'] = "Seleziona la larghezza e l'altezza dell'avatar in pixel.";
 
?>
