<?php
/**
 * TL_ROOT/system/modules/avatar/languages/it/tl_user.php 
 * 
 * TYPOlight extension: avatar 0.2.0 stable 
 * Italian translation file 
 * 
 * Copyright : (c) 2008 IBK Software AG 
 * License   : GNU GPL V3 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dan (dan), http://www.dss.uniud.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_user']['avatar']['0'] = "Avatar";
$GLOBALS['TL_LANG']['tl_user']['avatar']['1'] = "Qui puoi caricare un avatar o un logo.";
 
?>
