<?php
/**
 * TL_ROOT/system/modules/avatar/languages/cs/avatar.php 
 * 
 * Contao extension: avatar 1.0.1 stable 
 * Czech translation file 
 * 
 * Copyright : (c) 2008,2009,2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['avatar']['file']['0'] = "Nahrát nový avatar";
$GLOBALS['TL_LANG']['avatar']['file']['1'] = "Povolené typy souborů: %s.<br/>\nMaximální velikost souboru: %s bytes.<br/>\nMaximální rozměry: %s x %s pixels.";
$GLOBALS['TL_LANG']['avatar']['save'] = "Uložit avatar";
$GLOBALS['TL_LANG']['avatar']['reset'] = "Obnovit výchozí";
$GLOBALS['TL_LANG']['avatar']['invalidfilext'] = "<em>%s</em> má neplatnou extenzi.";
$GLOBALS['TL_LANG']['avatar']['errinisize'] = "<em>%s</em> překročena max_velikost_souboru_při_nahrávání v php.ini.";
$GLOBALS['TL_LANG']['avatar']['errformsize'] = "<em>%s</em> překročena MAX_VELIKOST_SOUBORU ve formuláři.";
$GLOBALS['TL_LANG']['avatar']['errpartial'] = "<em>%s</em> byl nahrán jen částečně.";
$GLOBALS['TL_LANG']['avatar']['notmpdir'] = "Chybí dočasná složka.";
$GLOBALS['TL_LANG']['avatar']['cantwrite'] = "<em>%s</em> nepodařilo se zapsat soubor na disk.";
$GLOBALS['TL_LANG']['avatar']['errorno'] = "<em>%s</em> chyba zapsání %s.";
$GLOBALS['TL_LANG']['avatar']['filetoobig'] = "<em>%s</em> překračuje povolenou maximální velikost.";
$GLOBALS['TL_LANG']['avatar']['imgtoobig'] = "<em>%s</em> přesahuje povolené rozměry.";
 
?>
