<?php
/**
 * TL_ROOT/system/modules/avatar/languages/fr/avatar.php 
 * 
 * Contao extension: avatar 1.0.1 stable 
 * French translation file 
 * 
 * Copyright : (c) 2008,2009,2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['avatar']['file']['0'] = "Télécharger un nouvel avatar";
$GLOBALS['TL_LANG']['avatar']['file']['1'] = "Type de fichiers autorisés : %s.<br/> Taille maximale du fichier : %s octets.<br/> Dimensions maximales : %s x %s pixels.";
$GLOBALS['TL_LANG']['avatar']['save'] = "Sauvegarder l'avatar";
$GLOBALS['TL_LANG']['avatar']['reset'] = "Remettre l'avatar par défaut";
$GLOBALS['TL_LANG']['avatar']['invalidfilext'] = "<em>%s</em> possède une extension non valide.";
$GLOBALS['TL_LANG']['avatar']['errinisize'] = "<em>%s</em> dépasse upload_max_filesize dans php.ini.";
$GLOBALS['TL_LANG']['avatar']['errformsize'] = "<em>%s</em> dépasse MAX_FILE_SIZE dans le formulaire.";
$GLOBALS['TL_LANG']['avatar']['errpartial'] = "<em>%s</em> a été partiellement envoyé.";
$GLOBALS['TL_LANG']['avatar']['notmpdir'] = "Un répertoire temporaire est manquant.";
$GLOBALS['TL_LANG']['avatar']['cantwrite'] = "<em>%s</em> n'a pas pu être écrit sur le disque..";
$GLOBALS['TL_LANG']['avatar']['errorno'] = "<em>%s</em> erreur d'envoi %s.";
$GLOBALS['TL_LANG']['avatar']['filetoobig'] = "<em>%s</em> dépasse la taille maximale autorisée.";
$GLOBALS['TL_LANG']['avatar']['imgtoobig'] = "<em>%s</em> dépasse les dimensions maximales autorisées.";
 
?>
