<?php
/**
 * TL_ROOT/system/modules/avatar/languages/fr/tl_settings.php 
 * 
 * Contao extension: avatar 1.0.1 stable 
 * French translation file 
 * 
 * Copyright : (c) 2008,2009,2010 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['avatar_legend'] = "Avatar";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['0'] = "Répertoire de base";
$GLOBALS['TL_LANG']['tl_settings']['avatar_dir']['1'] = "Sélectionnez le répertoire de base qui contiendra les avatars. Suggestion : <em>tl_files/avatars</em>";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['0'] = "Taille de fichier maximale";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxsize']['1'] = "Sélectionnez la taille de fichier maximale en octets.";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['0'] = "Dimensions maximales";
$GLOBALS['TL_LANG']['tl_settings']['avatar_maxdims']['1'] = "Sélectionnez la largeur et la hauteur maximale des avatars en pixels.";
 
?>
